Use updated KWAD Builder

diff --git a/.github/workflows/build.yml b/.github/workflows/build.yml
--- a/.github/workflows/build.yml
+++ b/.github/workflows/build.yml
@@ -25,16 +25,16 @@ jobs:
       # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
       - uses: actions/checkout@v2
           
-      - name: Download Example API from steam workshop
+      - name: Download KWAD Builder
         run: |
-          wget -q https://steamusercontent-a.akamaihd.net/ugc/358399162719791713/17B6973C6F60561466E081AEE0EF35ABC2FB19F2/ -O mod_publish_data_file.zip
+          wget -q https://cdn.discordapp.com/attachments/313015598789427202/565295702540812298/KWAD_builder.zip -O KWAD_builder.zip
           
       - name: Unzip Example API
-        run:  unzip -qq ./mod_publish_data_file.zip -d ./exampleapi || echo "Suppressing unzip errors"
+        run:  unzip -qq ./KWAD_builder.zip -d ./builder || echo "Suppressing unzip errors"
      
       - name: Make the mod using the given makefile
         run: |
-          sudo chmod +x exampleapi/KWAD\ builder/bin/linux/builder
+          sudo chmod +x builder/bin/linux/builder
           echo KWAD_BUILDER="./exampleapi/KWAD\ builder/bin/linux/builder" > makeconfig.mk
           echo INSTALL_PATH="./install" >> makeconfig.mk
           make install
